src/AuthServer.Web/Models/ErrorViewModel.cs
namespace AuthServer.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/AuthServer.Web/Models/LoginViewModel.cs
namespace AuthServer.Web.Models
{
    public record LoginViewModel(string ReturnUrl)
    {
        public string? UserName { get; init; }
        
        public string? Password { get; init; }
    }
}

src/AuthServer.Web/Models/SignUpViewModel.cs
using System;
using System.Collections.Generic;

namespace AuthServer.Web.Models
{
    public record SignUpViewModel(string ReturnUrl)
    {
        public string? UserName { get; set; }
        public string? Email { get; set; }
        public string? PhoneNumber { get; set; }
        public string? Password { get; set; }
        public string? PasswordConfirm { get; set; }

        public IReadOnlyList<string> Errors { get; set; } = Array.Empty<string>();
    }
}

src/AuthServer.Web/Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using AuthServer.Domain;
using AuthServer.Persistence.Repositories;
using AuthServer.Users;
using AuthServer.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace AuthServer.Web.Controllers
{
    [Route("auth")]
    public class AuthController : Controller
    {
        private readonly IUserRepository _userRepository;
        private readonly SignInManager<User> _signInManager;
        private readonly UserManager<User> _userManager;

        public AuthController(SignInManager<User> signInManager, IUserRepository userRepository, UserManager<User> userManager)
        {
            _signInManager = signInManager;
            _userRepository = userRepository;
            _userManager = userManager;
        }

        [HttpGet("login")]
        public IActionResult Login([FromQuery] string returnUrl)
        {
            ViewData["Title"] = "Login";
            return View(new LoginViewModel(returnUrl));
        }

        [HttpPost("login")]
        public async Task<IActionResult> Login(LoginViewModel vm)
        {
            var result = await _signInManager.PasswordSignInAsync(vm.UserName, vm.Password, true, false);

            if (result.Succeeded)
                return Redirect(vm.ReturnUrl ?? "/home");

            return View(new LoginViewModel(vm.ReturnUrl));
        }

        [HttpGet("signup")]
        public IActionResult SignUp([FromQuery] string returnUrl)
        {
            ViewData["Title"] = "Signup";
            return View(new SignUpViewModel(returnUrl));
        }

        [HttpPost("signup")]
        public async Task<IActionResult> SignUp(SignUpViewModel viewModel, CancellationToken cancellationToken)
        {
            var errors = await ValidateSignUp(viewModel, cancellationToken);

            if (errors.Any())
                return View(new SignUpViewModel(viewModel.ReturnUrl) { Errors = errors });

            var user = new User
            {
                Id = Guid.NewGuid(),
                UserName = viewModel.UserName,
                Email = viewModel.Email,
                PhoneNumber = viewModel.PhoneNumber
            };

            var result = await _userManager.CreateAsync(user, viewModel.Password);

            if (result.Succeeded && !string.IsNullOrWhiteSpace(viewModel.ReturnUrl))
                return Redirect(viewModel.ReturnUrl);

            return View(new SignUpViewModel(viewModel.ReturnUrl) { Errors = result.Errors.Select(x => x.Description).ToList() });
        }

        [HttpGet("authorized")]
        [Authorize(AuthenticationSchemes = "Identity.Application")]
        public IActionResult Auth()
        {
           return Ok(new { Haha = "haha" });
        }

        /// <summary>
        /// Validates signup view model 
        /// </summary>
        /// <returns> List of errors if model is not valid otherwise empty list </returns>
        private async ValueTask<IReadOnlyList<string>> ValidateSignUp(SignUpViewModel viewModel, CancellationToken cancellationToken)
        {
            var errors = new List<string>(4);

            if (string.IsNullOrWhiteSpace(viewModel.UserName))
                errors.Add("Username cannot be empty");

            // TODO: Add check for valid email
            if (string.IsNullOrWhiteSpace(viewModel.Email))
                errors.Add("Email cannot be empty");

            if (string.IsNullOrWhiteSpace(viewModel.Password))
                errors.Add("Password cannot be empty");

            if (viewModel.Password != viewModel.PasswordConfirm)
                errors.Add("Password and password confirmation are not the same");

            if (errors.Any())
                return errors;

            var filter = new UserFilter(viewModel.UserName, viewModel.Email);
            var exists = await _userRepository.ExistsAsync(filter, cancellationToken);
            if (exists)
                errors.Add("User with the same user name or email already exists");

            return errors;
        }
    }
}

src/AuthServer.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using AuthServer.Web.Models;

namespace AuthServer.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/AuthServer.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

src/AuthServer.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - AuthServer.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AuthServer.Web</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Login">Login</a>
                    </li>
                     <li class="nav-item">
                         <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="SignUp">SignUp</a>
                     </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2021 - AuthServer.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>